# Используем официальный образ OpenJDK
FROM openjdk:17-jdk-slim

# Указываем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем скомпилированный JAR файл в контейнер
COPY target/sharik-0.0.1-SNAPSHOT.jar /app/sharik-0.0.1-SNAPSHOT.jar

# Открываем порт для Spring Boot приложения (например, 8080)
EXPOSE 8080

# Команда для запуска приложения
ENTRYPOINT ["java", "-jar", "/app/sharik-0.0.1-SNAPSHOT.jar"]
