package com.mary.sharik.model.enums;

public enum KafkaTopicEnum {
    // PRODUCT
    PRODUCT_BY_FILTER_TOPIC,
    PRODUCT_BY_ID_TOPIC,
    PRODUCT_LIST_BY_IDS_TOPIC,
    PRODUCT_SET_STATUS_TOPIC,
    PRODUCT_CREATE_TOPIC,

    REPLY_TOPIC,

    //HISTORY + CART
    CART_EMPTY_TOPIC,
    CART_ADD_TOPIC,
    CART_CHANGE_AMOUNT_TOPIC,
    CART_ORDER_TOPIC,
    CART_VIEW_TOPIC,
    HISTORY_VIEW_TOPIC,
    HISTORY_ALL_TOPIC,

}